export default {
  'account-service.login.error.invalid-farmer': 'Could not find farmer for pool public key "{1}"',
  'account-service.login.success': 'Successfully logged in',
  'account-service.logout.success': 'Successfully logged out',
  'blocks-won-component.blocks-won-in-the-last-24h': '{1} in the last 24h',
  'blocks-won-component.distributed': 'Distributed',
  'blocks-won-component.header.date': 'Date',
  'blocks-won-component.header.distributed': 'Distributed',
  'blocks-won-component.header.height': 'Height',
  'blocks-won-component.header.network-capacity': 'Network Capacity',
  'blocks-won-component.header.reward': 'Reward',
  'blocks-won-component.header.winner': 'Winner',
  'blocks-won-component.no-blocks-won-yet': 'No blocks won yet!',
  'blocks-won-component.pending': 'Pending',
  'blocks-won-component.title': 'Recently won Blocks',
  'dashboard-component.latest-notices.title': 'Latest notices',
  'events-component.block-winner-extra-reward.title': 'Block winner extra rewards',
  'events-component.ended-at': 'Ended at',
  'events-component.extra-reward': 'Extra reward',
  'events-component.filled': 'Filled',
  'events-component.miner-extra-reward.title': 'Farmer extra rewards',
  'events-component.started-at': 'Started at',
  'events-component.state': 'State',
  'events-component.states.active': 'Active',
  'events-component.states.ended': 'Ended',
  'events-component.states.upcoming': 'Upcoming',
  'events-component.title': 'Events',
  'events-component.will-start': 'Will start',
  'faucet-component.binding-help-text': 'Use the "{1}" function in your wallet to bind to the pool ({2})',
  'faucet-component.errors.missing-address': 'No address entered!',
  'faucet-component.get-coins-to-bind': 'Get coins to bind',
  'faucet-component.input.address': 'Address',
  'faucet-component.pool-address': 'Pool address',
  'general.all': 'All',
  'general.distribution-ratio': 'Distribution ratio',
  'general.ec': 'Effective Capacity',
  'general.error': 'Error: {1}',
  'general.failure': 'Failure: {1}',
  'general.not-available.short': 'N/A',
  'general.success': 'Success!',
  'general.unknown': 'Unknown',
  'header-component.button.blocks-won': 'Blocks won',
  'header-component.button.dashboard': 'Dashboard',
  'header-component.button.events': 'Events',
  'header-component.button.faucet': 'Faucet',
  'header-component.button.info': 'Info',
  'header-component.button.logout': 'Logout',
  'header-component.button.my-farmer': 'My Farmer',
  'header-component.button.notices': 'Notices',
  'header-component.button.other-pools': 'Other Pools',
  'header-component.button.payouts': 'Payouts',
  'header-component.button.settings': 'Settings',
  'info-component.contact.join-discord': 'Join our <a href="https://discord.gg/gNHhn9y" target="_blank">Discord</a>',
  'info-component.contact.title': 'Contact',
  'info-component.pool-info.distribution-delay-info': 'Block reward distribution is delayed by {1} blocks',
  'info-component.pool-info.dr-info': 'Pool with support for any DR, default DR: {1}',
  'info-component.pool-info.payout.fee-info': '{1}% fee, free automatic payouts',
  'info-component.pool-info.payout.interval-info': 'Payouts happen once per day at 12:00 UTC',
  'info-component.pool-info.payout.minimum-info': 'Minimum amount for payouts is {1} {2}, every Sunday the minimum amount is ignored',
  'info-component.pool-info.pplns-info': 'PPLNS over the last {1} hours',
  'info-component.pool-info.title': 'Pool info',
  'info-component.using-this-pool.step-1': 'Download and install the pooling enabled <a href="https://github.com/felixbrucker/chia-blockchain" target="_blank">chia-blockchain</a> software',
  'info-component.using-this-pool.step-2': 'Add the <code>pool_url</code> config option in the farmer section of your chia <code>config.yaml</code> and set it to <code>{1}</code>',
  'info-component.using-this-pool.step-3': 'Add the <code>pool_payout_address</code> config option in the farmer section of your chia <code>config.yaml</code> and set it to your desired chia payout address',
  'info-component.using-this-pool.step-4': 'Run the pooling enabled chia-blockchain software',
  'info-component.using-this-pool.title': 'Using this pool',
  'my-farmer-component.difficulty-card.title': 'Difficulty',
  'my-farmer-component.last-partial-accepted-card.title': 'Last Partial accepted',
  'my-farmer-component.login-button.label': 'Login',
  'my-farmer-component.login-button.label-logging-in': 'Logging in',
  'my-farmer-component.name-card.title': 'Name',
  'my-farmer-component.payout-address-card.title': 'Payout Address',
  'my-farmer-component.pending-balance-card.title': 'Pending balance',
  'my-farmer-component.pool-pk-input.error.missing': 'No pool public key entered!',
  'my-farmer-component.pool-pk-input.placeholder': 'Pool Public Key',
  'my-farmer-component.pool-public-key-card.title': 'Pool Public Key',
  'notices-component.title': 'Notices',
  'payouts-component.headers.amount': 'Amount',
  'payouts-component.headers.date': 'Date',
  'payouts-component.headers.transaction': 'Transaction',
  'payouts-component.no-payouts-sent-yet': 'No payouts sent yet!',
  'payouts-component.title': 'Payouts',
  'routing.title-prefix.blocks-won': 'Blocks won',
  'routing.title-prefix.events': 'Events',
  'routing.title-prefix.faucet': 'Faucet',
  'routing.title-prefix.info': 'Info',
  'routing.title-prefix.notices': 'Notices',
  'routing.title-prefix.payouts': 'Payouts',
  'routing.title-prefix.settings': 'Settings',
  'routing.title-prefix.top-accounts': 'Top Accounts',
  'settings-component.actions.on-demand-payout.button': 'On demand payout',
  'settings-component.actions.on-demand-payout.help-text': 'Note: a {1} {2} flat fee is deducted from the on demand payout amount you specify. Minimum payout amount is {3} {2}.',
  'settings-component.actions.on-demand-payout.max': 'Max',
  'settings-component.actions.on-demand-payout.request-payout': 'Request payout',
  'settings-component.actions.on-demand-payout.success': 'Successfully requested a payout',
  'settings-component.actions.on-demand-payout.title': 'On demand payout',
  'settings-component.actions.set-account-name.account-name.placeholder': 'Account name',
  'settings-component.actions.set-account-name.button': 'Set account name',
  'settings-component.actions.set-account-name.save': 'Save',
  'settings-component.actions.set-account-name.success': 'Successfully set the account name',
  'settings-component.actions.set-account-name.title': 'Set account name',
  'settings-component.actions.set-distribution-ratio.button': 'Set distribution ratio',
  'settings-component.actions.set-distribution-ratio.help-text': 'Note: The distribution ratio defines how miner rewards are split. 0-100 gives 0% to the block winner and 100% to historical shares. 50-50 gives 50% to the block winner and 50% to historical shares. 100-0 gives 100% to the block winner and 0% to historical shares.',
  'settings-component.actions.set-distribution-ratio.save': 'Save',
  'settings-component.actions.set-distribution-ratio.success': 'Successfully set the distribution ratio',
  'settings-component.actions.set-distribution-ratio.title': 'Set distribution ratio',
  'settings-component.logged-in-with': 'Logged in with payout address {1}',
  'settings-component.logout': 'Logout',
  'settings-component.payout-address.placeholder': 'Your payout address',
  'settings-component.verification.button.label': 'Verify identity',
  'settings-component.verification.button.processing-label': 'Verifying identity',
  'settings-component.verification.message-to-sign': 'Message to sign',
  'settings-component.verification.public-key-input.label': 'Input your public key for verification',
  'settings-component.verification.public-key-input.placeholder': 'Your public key',
  'settings-component.verification.sign-it-here': 'Sign it here',
  'settings-component.verification.signature-input.label': 'Input your message signature for verification',
  'settings-component.verification.signature-input.placeholder': 'Message signature',
  'stats-card-component.balance-card.daily-reward': 'Daily Reward',
  'stats-card-component.balance-card.title': 'Pool Balance',
  'stats-card-component.farmers-card.title': 'Farmers | EC',
  'stats-card-component.height-card.elapsed': 'Elapsed',
  'stats-card-component.height-card.title': 'Height',
  'stats-card-component.network-capacity-card.network-capacity': 'Network Capacity',
  'stats-card-component.network-capacity-card.network-difficulty': 'Network Difficulty',
  'stats-card-component.network-capacity-card.title': 'Network Capacity | Network Difficulty',
  'top-accounts-component.headers.address': 'Address',
  'top-accounts-component.headers.capacity': 'Capacity',
  'top-accounts-component.headers.capacity.help-text': 'Reported capacity',
  'top-accounts-component.headers.deadlines': 'Deadlines',
  'top-accounts-component.headers.ec': 'EC',
  'top-accounts-component.headers.pending': 'Pending',
  'top-accounts-component.headers.share': 'Share',
  'top-accounts-component.headers.share.help-text': 'Historical share',
  'top-accounts-component.no-miners-found': 'No accounts found!',
  'top-accounts-component.one-state.offline': 'No submissions within the last 6 rounds',
  'top-accounts-component.one-state.online': 'Online',
  'top-accounts-component.one-state.warning': 'No submissions within the last 3 rounds',
  'top-accounts-component.search.placeholder': 'Search',
  'top-accounts-component.title': 'Top Accounts',
  'update-service.updating': 'Updating to the latest version ..',
};
